import type { Manager } from './types'

/** Моки менеджеров до появления API (страница «Менеджеры»). */
export const MOCK_MANAGERS: Manager[] = [
  {
    id: 'mgr-1',
    fullName: 'Петров Пётр Петрович',
    assignments: [],
    lofts: ['LOFT#1', 'LOFT#2'],
    halls: ['MAIN', 'BACKYARD'],
    activeProjectsCount: 12,
    closedProjectsCount: 34,
    salesTotal: 4_850_000,
    bonusTotal: 412_000,
  },
  {
    id: 'mgr-2',
    fullName: 'Сидоров Сидор Сидорович',
    assignments: [],
    lofts: ['LOFT#2', 'LOFT#3'],
    halls: ['BACKYARD', 'ROOFTOP'],
    activeProjectsCount: 8,
    closedProjectsCount: 21,
    salesTotal: 3_120_000,
    bonusTotal: 268_500,
  },
  {
    id: 'mgr-3',
    fullName: 'Петров Алексей',
    assignments: [],
    lofts: ['LOFT#1'],
    halls: ['MAIN'],
    activeProjectsCount: 5,
    closedProjectsCount: 18,
    salesTotal: 2_400_000,
    bonusTotal: 195_000,
  },
  {
    id: 'mgr-4',
    fullName: 'Сидорова Мария',
    assignments: [],
    lofts: ['LOFT#2'],
    halls: ['BACKYARD', 'ROOFTOP'],
    activeProjectsCount: 9,
    closedProjectsCount: 27,
    salesTotal: 3_680_000,
    bonusTotal: 301_200,
  },
  {
    id: 'mgr-5',
    fullName: 'Козлов Игорь Викторович',
    assignments: [],
    lofts: ['LOFT#1', 'LOFT#3'],
    halls: ['MAIN', 'ROOFTOP'],
    activeProjectsCount: 6,
    closedProjectsCount: 11,
    salesTotal: 1_950_000,
    bonusTotal: 156_800,
  },
]
