import type { Project } from '@/entities/project'

/** Моки для проверки UI страницы «Вне контура MAG» (только в dev). */
export const OUTSIDE_MAG_MOCK_PROJECTS: Project[] = [
  {
    id: 'mock-outside-1',
    title: 'Корпоратив Сбербанк — весенний ивент',
    date: '2026-06-14',
    stage: 'out_of_mag_scope',
    city: 'Москва',
    loft: 'LOFT#1',
    hall: 'MAIN',
    manager: 'Петров Алексей',
    type: 'Корпоратив',
    company: 'ПАО Сбербанк',
    phone: '+7 (495) 111-22-33',
    email: 'events@sber.mock',
    plumCardUrl: 'https://plum.mock/card/1',
    canClaim: false,
    canEdit: false,
    isReadOnly: false,
    isFromPlum: false,
    plumEventStatus: null,
    plumEventStatusLabel: null,
    updatedAt: '2026-05-25T12:00:00Z',
    createdAt: '2026-03-10T10:00:00Z',
    lastActiveStage: 'contract_signed',
  },
  {
    id: 'mock-outside-2',
    title: 'Свадьба Ивановых',
    date: '2026-07-20',
    stage: 'out_of_mag_scope',
    city: 'Санкт-Петербург',
    loft: 'LOFT#2',
    hall: 'BACKYARD',
    manager: 'Сидорова Мария',
    type: 'Свадьба',
    company: '',
    phone: '+7 (921) 555-66-77',
    email: 'ivanov.wedding@mock.ru',
    plumCardUrl: 'https://plum.mock/card/2',
    canClaim: false,
    canEdit: false,
    isReadOnly: false,
    isFromPlum: false,
    plumEventStatus: null,
    plumEventStatusLabel: null,
    updatedAt: '2026-05-27T09:00:00Z',
    createdAt: '2026-04-01T14:30:00Z',
    lastActiveStage: 'ready_to_event',
  },
  {
    id: 'mock-outside-3',
    title: 'Презентация новой линейки — закрытый показ',
    date: '2026-05-28',
    stage: 'out_of_mag_scope',
    city: 'Москва',
    loft: 'LOFT#3',
    hall: 'ROOFTOP',
    manager: 'Козлов Дмитрий',
    type: 'Презентация',
    company: 'ООО «Техно Бренд»',
    phone: '+7 (903) 444-55-66',
    email: 'pr@technobrand.mock',
    plumCardUrl: 'https://plum.mock/card/3',
    canClaim: false,
    canEdit: false,
    isReadOnly: false,
    isFromPlum: false,
    plumEventStatus: null,
    plumEventStatusLabel: null,
    updatedAt: '2026-05-26T15:23:00Z',
    createdAt: '2026-02-18T09:15:00Z',
    lastActiveStage: 'calculation_prepared',
  },
  {
    id: 'mock-outside-4',
    title: 'Детский праздник — день рождения',
    date: '2026-08-03',
    stage: 'out_of_mag_scope',
    city: 'Казань',
    loft: 'LOFT#1',
    hall: 'MAIN',
    manager: 'Петров Алексей',
    type: 'Частное мероприятие',
    company: 'Семья Кузнецовых',
    phone: '+7 (917) 222-33-44',
    email: '',
    plumCardUrl: 'https://plum.mock/card/4',
    canClaim: false,
    canEdit: false,
    isReadOnly: false,
    isFromPlum: false,
    plumEventStatus: null,
    plumEventStatusLabel: null,
    updatedAt: '2026-05-06T11:00:00Z',
    createdAt: '2026-01-22T11:00:00Z',
    lastActiveStage: 'primary_contact_done',
  },
  {
    id: 'mock-outside-5',
    title: 'Фестиваль уличной еды',
    date: '2026-09-12',
    stage: 'out_of_mag_scope',
    city: 'Москва',
    loft: 'LOFT#2',
    hall: 'ROOFTOP',
    manager: 'Новикова Елена',
    type: 'Фестиваль',
    company: 'ИП Новиков',
    phone: '+7 (926) 777-88-99',
    email: 'foodfest@mock.ru',
    plumCardUrl: 'https://plum.mock/card/5',
    canClaim: false,
    canEdit: false,
    isReadOnly: false,
    isFromPlum: false,
    plumEventStatus: null,
    plumEventStatusLabel: null,
    updatedAt: '2026-05-27T13:59:30Z',
    createdAt: '2026-05-01T08:45:00Z',
    lastActiveStage: 'event_held',
  },
  {
    id: 'mock-outside-6',
    title: 'Без зала и LOFT — черновик',
    date: '2026-10-01',
    stage: 'out_of_mag_scope',
    city: 'Москва',
    loft: '',
    hall: '',
    manager: '',
    type: 'Другое',
    company: '',
    phone: '+7 (900) 000-00-00',
    email: 'draft@mock.ru',
    plumCardUrl: 'https://plum.mock/card/6',
    canClaim: false,
    canEdit: false,
    isReadOnly: false,
    isFromPlum: false,
    plumEventStatus: null,
    plumEventStatusLabel: null,
    updatedAt: '2026-05-27T14:00:00Z',
    createdAt: '2026-05-19T16:00:00Z',
  },
]
