export type { Project, ProjectStatus } from './model/types'
export { mockProjects } from './model/mock'
export { groupByDay, toDayKey } from './lib/group-by-day'
export type { ProjectsByDay } from './lib/group-by-day'
export { getProjectsForDates, countProjectsInMonth } from './lib/schedule'
export type { ScheduleDayRow } from './lib/schedule'
export { pluralProjects } from './lib/plural'
export { ProjectCard } from './ui/project-card'
export { ProjectCountBadge } from './ui/project-count-badge'
export { ProjectStatusBadge } from './ui/project-status-badge'
